export const ErrorCodes = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  CONTENT_INVALID_LOCALE: 'CONTENT_INVALID_LOCALE',
  CONTENT_SLUG_TAKEN: 'CONTENT_SLUG_TAKEN',
  CONTENT_INCOMPLETE: 'CONTENT_INCOMPLETE',
  CONTENT_PRIMARY_DELETE_BLOCKED: 'CONTENT_PRIMARY_DELETE_BLOCKED',
  CONTENT_NOT_FOUND: 'CONTENT_NOT_FOUND',
  CONTENT_VALIDATION_FAILED: 'CONTENT_VALIDATION_FAILED',
  LEAD_NOT_FOUND: 'LEAD_NOT_FOUND',
  LEAD_WEBHOOK_INVALID: 'LEAD_WEBHOOK_INVALID',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
